### ISSUE TITLE
minio Deployment

### ISSUE THREAD

**Issue by mcrosson** [techknowlogick/caddy-s3browser#3]
Is there a standard way to deploy this with minio?

I've custom built caddy and cannot get it to work with the example in the readme with minio.

My minio deployment is running on a private IP with port 9000 in azure gateway mode.

The s3bucket plugin shows an empty directory but accessing the files directly yields a download.

Caddyfile for reference

```
dl.domain.com:80 dl.domain.com:443 {
    log /var/log/caddy/dl.log

    redir 301 {
        if {scheme} is http
        / https://dl.domain.com{uri}
    }

s3browser {
        key somekey
        secret longstring
        bucket downloads
        endpoint 172.30.12.11:9000
}

proxy / http://172.30.12.11:9000/downloads {
header_upstream Host dl.domain.com
}
}
```

**Comment by techknowlogick** [comment]
I think it might be that because my code assumes a TLS connection (it also assumes it is valid, and errors out when I use self-signed certs with minio), that when using plaintext HTTP it will error out. The specific line I need to change is https://github.com/techknowlogick/caddy-s3browser/blob/master/setup.go#L73

I will send a PR that allows this option to be swap between HTTPS connections, and HTTP connections. Then I will test again to see if that works.

For testing sake I am using minio as a gateway to azure to replicate as close to your setup as much as possible.

**Comment by mcrosson** [comment]
@techknowlogick Thank you so much for digging in 👍 

I really appreciate it!

**Comment by techknowlogick** [comment]
Np. I need this to work for me too, so really you are the one doing me a favour by reporting issues.

The only difference between your setup and my testing is I had a self signed cert on minio. However I've added a new option for the s3browser directive, if you set `secure false` then it'll go over plaintext HTTP. Would you be able to recompile Caddy with the updated plugin code, and try again?

**Comment by mcrosson** [comment]
@techknowlogick I just deployed an updated build and it's 100%

👍

**Comment by techknowlogick** [comment]
🎉  That's great news. I'm glad to hear that.
