### ISSUE TITLE
If I use proxy, do I still need this plugin?

### ISSUE THREAD

**Issue by cekvenich** [techknowlogick/caddy-s3browser#7]
Thank you for this project. I use S3 type a lot for website hosting.  I'm trying this out, it could help a lot. 

If I use proxy with header, it should get me the right files, eg from GCP.
So why do I need the key and secret?

Or asking differently, if I pass the key and secret, why do I need proxy and header when I have the files?

**Comment by techknowlogick** [comment]
Hi @cekvenich, thanks for the kind words 😄 

This caddy plugin provides a file list of the files from S3 (or minio) and so key/secret is needed so the plugin can fetch the file list from the S3 API and the proxy section is also needed so that users can also download the files.

You don't need this plugin if you want to provide downloads of the files, but already know what the path is.

I'm going to close this issue now, but please re-open if the above doesn't answer your question.
